#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 2 ]]; then
  echo "Usage: new-skill.sh <kebab-case-name> <purpose>"
  exit 1
fi

name="$1"
purpose="$2"

if [[ ! "${name}" =~ ^[a-z0-9]+(-[a-z0-9]+)*$ ]]; then
  echo "Invalid name: ${name}. Use kebab-case."
  exit 1
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
TARGET_DIR="${ROOT_DIR}/skills/${name}"
TEMPLATE="${ROOT_DIR}/skills/skill-authoring/assets/SKILL.template.md"

if [[ -e "${TARGET_DIR}" ]]; then
  echo "Skill already exists: ${TARGET_DIR}"
  exit 1
fi

mkdir -p "${TARGET_DIR}/scripts"

sed \
  -e "s/{{SKILL_NAME}}/${name}/g" \
  -e "s/{{PURPOSE}}/${purpose//\//\\/}/g" \
  "${TEMPLATE}" > "${TARGET_DIR}/SKILL.md"

cat > "${TARGET_DIR}/README.md" <<EOF
# ${name} Skill

Generated by skill-authoring scaffold.
EOF

cat > "${TARGET_DIR}/scripts/smoke.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
echo "smoke placeholder"
EOF

cat > "${TARGET_DIR}/scripts/run.sh" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
echo "run placeholder"
EOF

chmod +x "${TARGET_DIR}/scripts/smoke.sh" "${TARGET_DIR}/scripts/run.sh"

echo "Created skill scaffold: ${TARGET_DIR}"
